### ISSUE TITLE
Add example commit message to the README

### ISSUE THREAD

**Issue by bendodd** [concourse/tracker-resource#14]
Could we have an example git commit message that the resource would act upon?

**Comment by mariash** [comment]
Having an example directly in the README falls under the [duplicate effort](https://github.com/concourse/concourse/wiki/Anti-Patterns#duplicate-effort) antipattern, since tracker resource delegates parsing of commit messages to Pivotal Tracker. So instead, we just going to point to Pivotal Tracker syntax explanation page.
