### ISSUE TITLE
Getting `error fetching activity for story #XXXX: request failed (400)`

### ISSUE THREAD

**Issue by ljfranklin** [concourse/tracker-resource#17]
Since Feb 15th, our Tracker puts have been failing with `error fetching activity for story #XXXX: request failed (400)`. We verified that our token is valid. The convo from Slack speculated that Tracker changed their API, but we have not confirmed this: https://concourseci.slack.com/archives/general/p1487208130014225.

**Comment by cantino** [comment]
CredHub has also disabled our CI tracker integration due to this issue.

**Comment by rdy** [comment]
PCF Metrics App Dev has also disable the resource until this can be fixed

**Comment by mrasoahaingo** [comment]
I got the same error :(

**Comment by mmb** [comment]
The CLI team is also experiencing this issue and has disabled automatic story delivery in our pipeline.

**Comment by glyn** [comment]
The SCS team have also hit this issue.

**Comment by chendrix** [comment]
Hi all,

This issue has been fixed in the latest version of the tracker-resource. However, it has not yet been published as part of a new version of Concourse.

You can get the fixed functionality right now by redefining your tracker-resource. Add the following to your pipelines.

```
resource_types:
- name: tracker-resource
  type: docker-image
  source:
    repository: concourse/tracker-resource
```

And you will pull the latest (fixed) version of the tracker resource from Dockerhub.

**Comment by glyn** [comment]
Thanks @chendrix - very helpful.
